### ISSUE TITLE
ImagePullBackOff on Eirini pods

### ISSUE THREAD

**Issue by IvanHristov98** [cloudfoundry-community/eirini-on-microk8s#3] opened 2019-12-09 08:12 UTC
The deployment of Eirini works fine on microk8s except one problem. Whenever I try to **cf push** an app cf reaches this state where it is waiting for the app to start, but then it suddenly crashes.
After some time of debugging we notticed that the eirini pods cannot pull their OCI images from the bits registry.
After you **vagrant ssh** and then run **kubectl describe pod <your-app-pod> -n eirini** and scroll down to the bottom you notice the following error message showing up in a repetitive fashion:
_Failed to pull image "registry.192.168.51.101.nip.io:6666/cloudfoundry/6ae1bc72-6ed1-47f6-9ef9-47e9f3094da1:404498580387b44fc9c66f9cf3125031fe5c2514": rpc error: code = Unknown desc = failed to pull and unpack image "registry.192.168.51.101.nip.io:6666/cloudfoundry/6ae1bc72-6ed1-47f6-9ef9-47e9f3094da1:404498580387b44fc9c66f9cf3125031fe5c2514": failed to unpack image on snapshotter overlayfs: failed to extract layer sha256:be85ce3427c2ad0a505f79af746eaf023ae92e5929c35e53284e401e1c801318: mount callback failed on /var/snap/microk8s/common/var/lib/containerd/tmpmounts/containerd-mount628474653: unexpected EOF: unknown_
While still into the virtual machine the following steps were done:

> vagrant@ubuntu-bionic:\~$ ping registry.192.168.51.101.nip.io
> PING registry.192.168.51.101.nip.io (192.168.51.101) 56(84) bytes of data.
> 64 bytes from ubuntu-bionic (192.168.51.101): icmp_seq=1 ttl=64 time=0.019 ms
> 64 bytes from ubuntu-bionic (192.168.51.101): icmp_seq=2 ttl=64 time=0.028 ms
> 64 bytes from ubuntu-bionic (192.168.51.101): icmp_seq=3 ttl=64 time=0.041 ms
> 64 bytes from ubuntu-bionic (192.168.51.101): icmp_seq=4 ttl=64 time=0.057 ms
> ^C
> --- registry.192.168.51.101.nip.io ping statistics ---
> 4 packets transmitted, 4 received, 0% packet loss, time 3050ms
> rtt min/avg/max/mdev = 0.019/0.036/0.057/0.014 ms
> vagrant@ubuntu-bionic:~$ ping registry.192.168.51.101.nip.io:6666
> ping: registry.192.168.51.101.nip.io:6666: Name or service not known

The version of eirini is directly pulled from master branch. At the time of the occurence of this issue the latest commit on master branch is **62df11f**.
We reproduced the issue on both windows and macOS.
PS - The issue might be due to an untrusted CA.

@georgethebeatle @gdankov

**Comment by giner** [comment] 2019-12-09 08:59
Resources-wise (disk space, ram, cpu) everything is fine?

**Comment by giner** [comment] 2019-12-09 09:12
Can you get any useful logs from k8s itself and kubelet in particular?

**Comment by IvanHristov98** [comment] 2019-12-09 09:18
Not very useful.

**Comment by IvanHristov98** [comment] 2019-12-09 09:20
I receive the same cf logs as in this issue:
https://github.com/cloudfoundry-community/eirini-on-microk8s/issues/2#issuecomment-561119154

**Comment by giner** [comment] 2019-12-09 09:39
Hm... If only I could reproduce it.

Somebody mentioned a probably similar issue on Slack but with little details https://cloudfoundry.slack.com/archives/C8RU3BZ26/p1575038638230000?thread_ts=1575038638.230000&cid=C8RU3BZ26

**Comment by giner** [comment] 2019-12-09 09:49
What about blobstore logs?

**Comment by IvanHristov98** [comment] 2019-12-09 11:45
As for reproducing - the only thing needed to do so is to run **vagrant up** and the **cf push** an application.
I just tried the following. Ran **vagrant up** and waited until all the pods in the scf namespace had started running except the bits service pod (because it usually takes too long). And so while the bits pod was still initializing I ran a **cf push** of an application and it turned out give me the same error state of _ImagePullBackOff_ as if the bits service was up and running.

As for blobstore logs - After running:

> kubectl logs -n scf blobstore-0 blobstore 
> kubectl logs -n scf blobstore-0 loggregator

there was nothing new written to them.

**Comment by giner** [comment] 2019-12-09 11:53
Well, if bits is not running when you push this is something expected to be happening. You have to wait until bits is up.

**Comment by IvanHristov98** [comment] 2019-12-09 11:54
I know. The thing is that even with bits being up I receive the same problem.

**Comment by giner** [comment] 2019-12-09 11:58
This is what I cannot reproduce. Can you try to understand what's happening between kubelet -> bits -> blobstore with tcpdump and may be strace when bits is running?

**Comment by giner** [comment] 2019-12-09 13:21
Not kubelet but containerd though is the one which is responsible for downloading the image from bits iirc.

**Comment by IvanHristov98** [comment] 2019-12-09 15:40
After analysing with **tcpdump** and traversing a lot of logs I can confirm that the droplet is successfully created and added to blobstore.
On the other side the results from running:
```
> sudo docker login -u admin -p Ahtoh2phabie https://registry.192.168.51.101.nip.io
Error response from daemon: Get https://registry.192.168.51.101.nip.io/v2/: x509: certificate signed by unknown authority
> curl https://registry.192.168.51.101.nip.io/v2/
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
don't make sense because after running:
`> cat ca-certificates.crt | less`
the certificate that the bits service is using is within it.

**Comment by IvanHristov98** [comment] 2019-12-09 17:32
Run:
```
> kubectl exec -it -nscf <bits-pod-name> /bin/bash
> cd assets
> vim eirinifs.tar
...
usr/lib/x86_64-linux-gnu/libxcb.so
usr/lib/x86_64-linux-gnu/libxcb.so.1
usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```
That EOF explains the _unexpected EOF: unknown_ error from above.
It seems as **Bits service** has a default timeout for downloading **eirinifs.tar** and depending on your network connectivity it could stop without returning an exit status of >0.
The init container of the bits pod is **download-eirini-rootfs** and as seen from:
`kubectl describe pod <bits-pod-name> -nscf`
it uses the:
```
Command:
      /bin/sh
      -c
      ./eirini-rootfs-downloader.sh

```
that executes the following script:
https://github.com/cloudfoundry-incubator/bits-service-release/blob/master/docker/eirini-rootfs-downloader/eirini-rootfs-downloader.sh
that calls:
```
function download_rootfs_tar
{
    curl -X GET -L $(curl https://api.github.com/repos/cloudfoundry-incubator/eirinifs/releases/tags/${EIRINI_ROOTFS_VERSION} | jq '.assets[].browser_download_url' | tr -d '\"') --output ${ASSETS_PATH}/eirinifs.tar
}
```
but curl has a default timeout and it's exit status is never taken into account, hence it silently stops downloading the tar file and continues normal execution as if no error has ever occurred. And that's how we end up with a corrupted **eirinifs.tar** file.
Still don't know if that fixes the problem.

**Comment by giner** [comment] 2019-12-09 23:34
Nice catch! I would expect the failures of downloading rootfs to be reflected in `bits` pod events. Are they?

**Comment by gdankov** [comment] 2019-12-10 08:14
@giner Looks like there's a bug in the `eirini-rootfs-downloader` script -- it doesn't exit with a non-zero code if any of the commands fail. That's why the init container completes and bits service is started with the corrupted rootfs.

**Comment by giner** [comment] 2019-12-10 09:14
@gdankov it was my thought also. I checked the current master and found that while the `curl` failure is not handled explicitly it still should fail due to `-e` option for bash. There is one thing though I don't know yet, what happens after the failure? Would the download restart, find partially downloaded file and skip downloading with success?

**Comment by gdankov** [comment] 2019-12-10 09:24
@giner Good point, that's probably what will happen. 

We'll have to either (1) validate the tar with a checksum if it's already there or (2) immediately delete it on failure.

**Comment by IvanHristov98** [comment] 2019-12-10 09:29
Some update - I manually downloaded the tar file from github, replaced the corrupted one with it. Then what happened is that yesterday I made a cf push of an app straight after it and the ImagePullBackOff issue was still present. This morning (~12 hours later) I made another attempt to push the same app and it worked properly.
So I am starting to think that perhaps the content of **eirinifs.tar** is loaded somewhere in memory.

**Comment by giner** [comment] 2019-12-10 09:31
@gdankov putting all together plus downloading to a temporary file
```
curl_download (with Continue/Resume option) to temp_file

if curl_download is success then
    check_sum
else
    exit (or retry a few times before exiting)
end if

if check_sum is success then
    rename temp_file to eirinifs.tar
else
    delete file
    exit
end if
```

**Comment by giner** [comment] 2019-12-10 09:32
Also `curl` is capable of resuming the interrupted download using option `-C -`.

**Comment by IvanHristov98** [comment] 2019-12-10 09:34
Then perhaps the correct workflow would be validate with the checksum, if ok -> rename, if not ok-> use the continue option?

**Comment by giner** [comment] 2019-12-10 09:43
Retrying on `curl succeeds + checksum is not ok` may result in the endless loop where downloading is finished but not correct for some reason.

**Comment by IvanHristov98** [comment] 2019-12-10 11:02
Wouldn't that be possible only if the file that curl tries to download is itself corrupted. Please provide an example scenario where this endless loop could occur.

**Comment by giner** [comment] 2019-12-10 19:03
To track the issue: https://www.pivotaltracker.com/n/projects/2172361/stories/170204256

**Comment by giner** [comment] 2019-12-19 00:20
> Wouldn't that be possible only if the file that curl tries to download is itself corrupted. Please provide an example scenario where this endless loop could occur.

The most frequent (but not the only one) scenario is when the downloading is happening through an http proxy and the proxy replies with an error message. The client (curl) will take it for a successful download. If this happens `curl -C - ...` may append file on the next request up to the original image size but the checksum will never match.

**Comment by giner** [comment] 2020-01-08 00:02
Should be fixed by https://github.com/cloudfoundry-incubator/eirini-release/commit/70bdd4cc9b4cb1567973a88534968df870ef4ec0 and https://github.com/cloudfoundry-incubator/bits-service-release/commit/699d49687af2321b5c49bf396f1ea36757dd93fa. Can you give it a try?

**Comment by IvanHristov98** [comment] 2020-01-09 12:18
Nope. At least there is a slight improvement. The init container `download-eirini-rootfs` terminates with an error, thus not letting the `bits` container start, and leaving it in `PodInitializing` state. From pod description:
```
Command:
      /bin/sh
      -c
      ./eirini-rootfs-downloader.sh
    State:          Running
      Started:      Thu, 09 Jan 2020 07:39:32 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    56
      Started:      Thu, 09 Jan 2020 07:09:32 +0000
      Finished:     Thu, 09 Jan 2020 07:39:31 +0000
    Ready:          False
```
Init container logs can be viewed here - [Eirini rootfs logs](https://pastebin.com/pV4e29AG)

When ssh-ed into `download-eirini-rootfs` container, the temporary `eirinifs.tar.${EIRINI_ROOTFS_VERSION}.downloading` file is still not replaced.

**Comment by giner** [comment] 2020-01-09 12:23
How big is the file? Is it growing?

**Comment by IvanHristov98** [comment] 2020-01-09 12:28
It has stopped at 520M with a `Restart Count: 2` of the init container. Perhaps the biggest issue is my slow network connection.

**Comment by giner** [comment] 2020-01-09 12:39
Should eventually finish downloading after a few restarts

**Comment by IvanHristov98** [comment] 2020-01-09 14:47
The problem is that it stops and there are no further restarts.

**Comment by giner** [comment] 2020-01-09 14:54
After 6 tries I suppose?

**Comment by IvanHristov98** [comment] 2020-01-09 14:57
After 3 tries, and there is no restart after the third which is awkward. Maybe exit status 56 lies behind this, I don't know.

**Comment by giner** [comment] 2020-01-09 21:17
From the logs you shared it looks as if the init container was still running but downloading is very slow (note the time left in the curl output).

**Comment by IvanHristov98** [comment] 2020-01-10 08:35
It works. I restarted the cluster and it seems as it truely was downloading with a speed of 0. It now continued the downloaded and after 5 additional restarts, it downloaded the whole eirinifs.tar. Then I simply tested it with the staticfile example from the repo and it now works properly.

So I think this wraps it up and we can close the issue.

**Closed as completed** 2020-01-10 09:21 UTC

**Comment by giner** [comment] 2020-01-10 09:26
@IvanHristov98 thank you for your feedback!
